title: Huong Trang
email: dothihuongtrang@gmail.com
markdown: kramdown
theme: null

# Collection cho Life Journal
collections:
  journal:
    output: true
    permalink: /journal/:name/

exclude:
  - node_modules
  - gulpfile.js
  - package.json

